version: '3'
volumes:
  pkg:
services:
  app:
    container_name: nuxt-app
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - pkg:/app/node_modules
    ports:
      - "3000:3000"
